name: sync_player
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  json_annotation: ^4.3.0
  permission_handler: ^12.0.0+1
  audio_metadata_reader: ^1.1.2
  audiotags: ^1.4.5
  mime: ^2.0.0
  provider: ^6.1.4
  musicbrainz_api_client: ^0.1.7
  audio_service: ^0.18.7
  audio_session: ^0.2.1
  just_audio: ^0.10.2
  just_audio_media_kit: ^2.1.0
  http: ^1.4.0
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  uuid: ^4.5.1
  crypto: ^3.0.6
  media_kit_libs_linux: ^1.2.1
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/

